//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LillysBeauty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Days
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Days()
        {
            this.TimeSlots = new HashSet<TimeSlots>();
        }
    
        public int Id { get; set; }
        public int MonthsId { get; set; }
        public int Day { get; set; }
        public bool Available { get; set; }
    
        public virtual Months Months { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSlots> TimeSlots { get; set; }
    }
}
