//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LillysBeauty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Months
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Months()
        {
            this.Days = new HashSet<Days>();
        }
    
        public int Id { get; set; }
        public int YearsId { get; set; }
        public int Month { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Days> Days { get; set; }
        public virtual Years Years { get; set; }
    }
}
